# Generated by Django 3.0.5 on 2020-04-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='youtube_video_id',
        ),
    ]
